version: "3.9"

services:
  postgres:
    image: postgres:16
    container_name: catalog_postgres
    restart: always
    environment:
      POSTGRES_USER: catalog_user
      POSTGRES_PASSWORD: catalog_pass
      POSTGRES_DB: catalog_db
    ports:
      - "5433:5432"
   
  redis:
    image: redis:latest
    container_name: redis_cache
    restart: always
    ports:
      - "6379:6379"
    # volumes:
    #   - redis_data:/var/lib/redis

  rabbitmq:
    image: rabbitmq:3-management
    container_name: rabbitmq
    ports:
       - "5672:5672"     # AMQP protocol
       - "15672:15672"   # Management UI
    environment:
       - RABBITMQ_DEFAULT_USER=guest
       - RABBITMQ_DEFAULT_PASS=guest
    # volumes:
    #    - rabbitmq_data:/var/lib/rabbitmq


  yarpapigateway:
    image: ${DOCKER_REGISTRY-}yarpapigateway
    build:
      context: .
      dockerfile: ApiGateway/YarpApiGateway/Dockerfile

  catalog.api:
    image: ${DOCKER_REGISTRY-}catalogapi
    build:
      context: .
      dockerfile: Services/Catalog/Catalog.API/Dockerfile

  cart.api:
    image: ${DOCKER_REGISTRY-}cartapi
    build:
      context: .
      dockerfile: Services/Cart/Cart.API/Dockerfile

  discount.grpc:
    image: ${DOCKER_REGISTRY-}discountgrpc
    build:
      context: .
      dockerfile: Services/Discount/Discount.gRPC/Dockerfile

