// <auto-generated />
using System;
using Catalog.API.Data;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;

#nullable disable

namespace Catalog.API.Migrations
{
    [DbContext(typeof(ProductDbContext))]
    [Migration("20251126093509_ProductCategory")]
    partial class ProductCategory
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "8.0.0")
                .HasAnnotation("Relational:MaxIdentifierLength", 63);

            NpgsqlModelBuilderExtensions.UseIdentityByDefaultColumns(modelBuilder);

            modelBuilder.Entity("Catalog.API.Models.Category", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<string>("Description")
                        .IsRequired()
                        .HasMaxLength(1000)
                        .HasColumnType("character varying(1000)");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(300)
                        .HasColumnType("character varying(300)");

                    b.HasKey("Id");

                    b.ToTable("Categories");

                    b.HasData(
                        new
                        {
                            Id = new Guid("40d4a750-812b-4364-9027-676bea89216d"),
                            Description = "Apparel for men",
                            Name = "Men's Clothing"
                        },
                        new
                        {
                            Id = new Guid("ca41a2c8-bd56-4c12-9efb-944109a7d404"),
                            Description = "Apparel for women",
                            Name = "Women's Clothing"
                        },
                        new
                        {
                            Id = new Guid("3c7d953e-61fa-47cb-b263-30c55f364f7d"),
                            Description = "Apparel for children",
                            Name = "Kids' Clothing"
                        },
                        new
                        {
                            Id = new Guid("7c8006ab-4dbe-40b2-8876-08fa113cf986"),
                            Description = "Shoes, boots, sneakers",
                            Name = "Footwear"
                        },
                        new
                        {
                            Id = new Guid("3d87cbf9-e79c-4833-8374-84b0858925c8"),
                            Description = "Belts, hats, scarves, bags",
                            Name = "Accessories"
                        },
                        new
                        {
                            Id = new Guid("a5a9e340-9c8b-43c6-ac90-04162e2a8109"),
                            Description = "Activewear, gym clothes",
                            Name = "Sportswear"
                        },
                        new
                        {
                            Id = new Guid("def16ffb-17bb-45b6-a192-e10143a6eaa4"),
                            Description = "Comfortable home clothing",
                            Name = "Loungewear"
                        },
                        new
                        {
                            Id = new Guid("debcc794-3754-4e80-a031-5e771f2dfc27"),
                            Description = "Jackets, coats",
                            Name = "Outerwear"
                        },
                        new
                        {
                            Id = new Guid("f2592271-553c-48b2-a8b9-38c751d3567e"),
                            Description = "Suits, dresses, gowns",
                            Name = "Formal Wear"
                        },
                        new
                        {
                            Id = new Guid("84d834cd-d647-4768-9350-94327748afcd"),
                            Description = "Underwear, pajamas, nightwear",
                            Name = "Underwear & Sleepwear"
                        });
                });

            modelBuilder.Entity("Catalog.API.Models.Product", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("Description")
                        .IsRequired()
                        .HasMaxLength(1000)
                        .HasColumnType("character varying(1000)");

                    b.Property<string>("ImageFile")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<bool>("IsAvailable")
                        .HasColumnType("boolean");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(300)
                        .HasColumnType("character varying(300)");

                    b.Property<decimal>("Price")
                        .HasColumnType("numeric");

                    b.Property<int>("Rating")
                        .HasColumnType("integer");

                    b.Property<string>("Sku")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<DateTime>("UpdatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.HasKey("Id");

                    b.ToTable("Products");

                    b.HasData(
                        new
                        {
                            Id = new Guid("0a1819eb-0f56-417b-aecb-08c038047248"),
                            CreatedAt = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Description = "100% cotton, comfortable fit",
                            ImageFile = "mens-classic-tshirt.jpg",
                            IsAvailable = true,
                            Name = "Men's Classic T-Shirt",
                            Price = 25.99m,
                            Rating = 4,
                            Sku = "MEN-TSHIRT-01",
                            UpdatedAt = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified)
                        },
                        new
                        {
                            Id = new Guid("7c7a8e8e-6926-422a-9e8c-232932e4d47d"),
                            CreatedAt = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Description = "Denim, slim fit, dark wash",
                            ImageFile = "mens-slim-jeans.jpg",
                            IsAvailable = true,
                            Name = "Men's Slim Jeans",
                            Price = 49.99m,
                            Rating = 5,
                            Sku = "MEN-JEANS-02",
                            UpdatedAt = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified)
                        },
                        new
                        {
                            Id = new Guid("2d787418-ff8f-4d6d-b29d-3d2b7c062ecf"),
                            CreatedAt = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Description = "Lightweight, floral print",
                            ImageFile = "womens-summer-dress.jpg",
                            IsAvailable = true,
                            Name = "Women's Summer Dress",
                            Price = 39.99m,
                            Rating = 5,
                            Sku = "WOM-DRESS-01",
                            UpdatedAt = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified)
                        },
                        new
                        {
                            Id = new Guid("f53ec6d4-0927-4b42-8799-b7824549c53d"),
                            CreatedAt = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Description = "Silk blend, long sleeves",
                            ImageFile = "womens-blouse.jpg",
                            IsAvailable = true,
                            Name = "Women's Blouse",
                            Price = 35.50m,
                            Rating = 4,
                            Sku = "WOM-BLOUSE-02",
                            UpdatedAt = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified)
                        },
                        new
                        {
                            Id = new Guid("a9278579-5a6e-4b5d-9693-78eca5817d05"),
                            CreatedAt = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Description = "Soft cotton, colorful design",
                            ImageFile = "kids-hoodie.jpg",
                            IsAvailable = true,
                            Name = "Kids' Hoodie",
                            Price = 29.99m,
                            Rating = 4,
                            Sku = "KID-HOODIE-01",
                            UpdatedAt = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified)
                        },
                        new
                        {
                            Id = new Guid("540a8135-cbd8-4bb3-858d-a3347cc9d16d"),
                            CreatedAt = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Description = "Lightweight and durable",
                            ImageFile = "kids-sneakers.jpg",
                            IsAvailable = true,
                            Name = "Kids' Sneakers",
                            Price = 34.99m,
                            Rating = 5,
                            Sku = "KID-SNEAK-01",
                            UpdatedAt = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified)
                        },
                        new
                        {
                            Id = new Guid("a2b9d992-e3e4-4e9b-8f2a-1ceff976d5ab"),
                            CreatedAt = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Description = "Genuine leather, classic buckle",
                            ImageFile = "leather-belt.jpg",
                            IsAvailable = true,
                            Name = "Leather Belt",
                            Price = 19.99m,
                            Rating = 4,
                            Sku = "ACC-BELT-01",
                            UpdatedAt = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified)
                        },
                        new
                        {
                            Id = new Guid("796073c9-87e2-41b6-b742-f58c4ce8311f"),
                            CreatedAt = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Description = "Lightweight with cushioned sole",
                            ImageFile = "mens-running-shoes.jpg",
                            IsAvailable = true,
                            Name = "Men's Running Shoes",
                            Price = 89.99m,
                            Rating = 5,
                            Sku = "MEN-RUN-01",
                            UpdatedAt = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified)
                        },
                        new
                        {
                            Id = new Guid("21853cd8-c563-4266-a0a3-80576ccbd164"),
                            CreatedAt = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Description = "Stretchable and comfortable",
                            ImageFile = "womens-yoga-pants.jpg",
                            IsAvailable = true,
                            Name = "Women's Yoga Pants",
                            Price = 45.00m,
                            Rating = 4,
                            Sku = "WOM-YOGA-01",
                            UpdatedAt = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified)
                        },
                        new
                        {
                            Id = new Guid("936f8bec-3b59-4b87-a315-a5914c3c9af7"),
                            CreatedAt = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Description = "Waterproof and insulated",
                            ImageFile = "winter-jacket.jpg",
                            IsAvailable = true,
                            Name = "Winter Jacket",
                            Price = 129.99m,
                            Rating = 5,
                            Sku = "OUT-JACKET-01",
                            UpdatedAt = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified)
                        },
                        new
                        {
                            Id = new Guid("9fe80821-3cf3-48f4-b674-1a8079beea59"),
                            CreatedAt = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Description = "Tailored fit, premium fabric",
                            ImageFile = "mens-suit.jpg",
                            IsAvailable = true,
                            Name = "Men's Suit",
                            Price = 249.99m,
                            Rating = 5,
                            Sku = "FORM-SUIT-01",
                            UpdatedAt = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified)
                        },
                        new
                        {
                            Id = new Guid("e66d1bec-0a22-47a5-8b3e-ce7eadc94863"),
                            CreatedAt = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Description = "Elegant floor-length gown",
                            ImageFile = "womens-evening-gown.jpg",
                            IsAvailable = true,
                            Name = "Women's Evening Gown",
                            Price = 199.99m,
                            Rating = 5,
                            Sku = "FORM-GOWN-01",
                            UpdatedAt = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified)
                        },
                        new
                        {
                            Id = new Guid("4d03f9af-1097-414a-b704-213a95e36b72"),
                            CreatedAt = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Description = "Soft cotton top and pants",
                            ImageFile = "loungewear-set.jpg",
                            IsAvailable = true,
                            Name = "Loungewear Set",
                            Price = 59.99m,
                            Rating = 4,
                            Sku = "LOUNGE-SET-01",
                            UpdatedAt = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified)
                        },
                        new
                        {
                            Id = new Guid("7293599c-6113-4303-b1c9-01c81e762166"),
                            CreatedAt = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Description = "Comfortable nightwear",
                            ImageFile = "mens-pajama-set.jpg",
                            IsAvailable = true,
                            Name = "Men's Pajama Set",
                            Price = 39.99m,
                            Rating = 4,
                            Sku = "UNDER-MEN-01",
                            UpdatedAt = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified)
                        },
                        new
                        {
                            Id = new Guid("dcb09d99-4e56-4bfe-bbb9-34fa8f67c56c"),
                            CreatedAt = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Description = "Soft and cozy sleepwear",
                            ImageFile = "womens-pajama-set.jpg",
                            IsAvailable = true,
                            Name = "Women's Pajama Set",
                            Price = 42.99m,
                            Rating = 5,
                            Sku = "UNDER-WOM-01",
                            UpdatedAt = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified)
                        },
                        new
                        {
                            Id = new Guid("b31becfe-cd73-42dd-98be-171c20f672a7"),
                            CreatedAt = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Description = "Waterproof and insulated",
                            ImageFile = "kids-winter-boots.jpg",
                            IsAvailable = true,
                            Name = "Kids' Winter Boots",
                            Price = 59.99m,
                            Rating = 5,
                            Sku = "KID-BOOT-01",
                            UpdatedAt = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified)
                        },
                        new
                        {
                            Id = new Guid("378690c5-295d-4955-8860-abbed9c2c9ab"),
                            CreatedAt = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Description = "Breathable material, adjustable",
                            ImageFile = "sports-cap.jpg",
                            IsAvailable = true,
                            Name = "Sports Cap",
                            Price = 14.99m,
                            Rating = 4,
                            Sku = "ACC-CAP-01",
                            UpdatedAt = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified)
                        },
                        new
                        {
                            Id = new Guid("0c02c7af-5bcf-4166-8c9a-974e4e5222ec"),
                            CreatedAt = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Description = "Casual and sporty",
                            ImageFile = "womens-sneakers.jpg",
                            IsAvailable = true,
                            Name = "Sneakers for Women",
                            Price = 79.99m,
                            Rating = 4,
                            Sku = "WOM-SNEAK-01",
                            UpdatedAt = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified)
                        },
                        new
                        {
                            Id = new Guid("15077ff2-a784-4746-9ba4-5f26cb28bf11"),
                            CreatedAt = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Description = "Durable and spacious",
                            ImageFile = "backpack.jpg",
                            IsAvailable = true,
                            Name = "Backpack",
                            Price = 49.99m,
                            Rating = 4,
                            Sku = "ACC-BAG-01",
                            UpdatedAt = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified)
                        },
                        new
                        {
                            Id = new Guid("d65d91ae-99e4-48c4-a77a-cd495cb9761f"),
                            CreatedAt = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Description = "Warm and stylish",
                            ImageFile = "mens-hoodie.jpg",
                            IsAvailable = true,
                            Name = "Men's Hoodie",
                            Price = 59.99m,
                            Rating = 4,
                            Sku = "MEN-HOODIE-01",
                            UpdatedAt = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified)
                        });
                });

            modelBuilder.Entity("Catalog.API.Models.ProductCategory", b =>
                {
                    b.Property<Guid>("ProductId")
                        .HasColumnType("uuid");

                    b.Property<Guid>("CategoryId")
                        .HasColumnType("uuid");

                    b.HasKey("ProductId", "CategoryId");

                    b.HasIndex("CategoryId");

                    b.ToTable("ProductCategories");

                    b.HasData(
                        new
                        {
                            ProductId = new Guid("0a1819eb-0f56-417b-aecb-08c038047248"),
                            CategoryId = new Guid("40d4a750-812b-4364-9027-676bea89216d")
                        },
                        new
                        {
                            ProductId = new Guid("7c7a8e8e-6926-422a-9e8c-232932e4d47d"),
                            CategoryId = new Guid("40d4a750-812b-4364-9027-676bea89216d")
                        },
                        new
                        {
                            ProductId = new Guid("2d787418-ff8f-4d6d-b29d-3d2b7c062ecf"),
                            CategoryId = new Guid("ca41a2c8-bd56-4c12-9efb-944109a7d404")
                        },
                        new
                        {
                            ProductId = new Guid("f53ec6d4-0927-4b42-8799-b7824549c53d"),
                            CategoryId = new Guid("ca41a2c8-bd56-4c12-9efb-944109a7d404")
                        },
                        new
                        {
                            ProductId = new Guid("a9278579-5a6e-4b5d-9693-78eca5817d05"),
                            CategoryId = new Guid("3c7d953e-61fa-47cb-b263-30c55f364f7d")
                        },
                        new
                        {
                            ProductId = new Guid("540a8135-cbd8-4bb3-858d-a3347cc9d16d"),
                            CategoryId = new Guid("3c7d953e-61fa-47cb-b263-30c55f364f7d")
                        },
                        new
                        {
                            ProductId = new Guid("a2b9d992-e3e4-4e9b-8f2a-1ceff976d5ab"),
                            CategoryId = new Guid("3d87cbf9-e79c-4833-8374-84b0858925c8")
                        },
                        new
                        {
                            ProductId = new Guid("796073c9-87e2-41b6-b742-f58c4ce8311f"),
                            CategoryId = new Guid("40d4a750-812b-4364-9027-676bea89216d")
                        },
                        new
                        {
                            ProductId = new Guid("21853cd8-c563-4266-a0a3-80576ccbd164"),
                            CategoryId = new Guid("ca41a2c8-bd56-4c12-9efb-944109a7d404")
                        },
                        new
                        {
                            ProductId = new Guid("936f8bec-3b59-4b87-a315-a5914c3c9af7"),
                            CategoryId = new Guid("debcc794-3754-4e80-a031-5e771f2dfc27")
                        },
                        new
                        {
                            ProductId = new Guid("9fe80821-3cf3-48f4-b674-1a8079beea59"),
                            CategoryId = new Guid("40d4a750-812b-4364-9027-676bea89216d")
                        },
                        new
                        {
                            ProductId = new Guid("e66d1bec-0a22-47a5-8b3e-ce7eadc94863"),
                            CategoryId = new Guid("ca41a2c8-bd56-4c12-9efb-944109a7d404")
                        },
                        new
                        {
                            ProductId = new Guid("4d03f9af-1097-414a-b704-213a95e36b72"),
                            CategoryId = new Guid("def16ffb-17bb-45b6-a192-e10143a6eaa4")
                        },
                        new
                        {
                            ProductId = new Guid("7293599c-6113-4303-b1c9-01c81e762166"),
                            CategoryId = new Guid("84d834cd-d647-4768-9350-94327748afcd")
                        },
                        new
                        {
                            ProductId = new Guid("dcb09d99-4e56-4bfe-bbb9-34fa8f67c56c"),
                            CategoryId = new Guid("84d834cd-d647-4768-9350-94327748afcd")
                        },
                        new
                        {
                            ProductId = new Guid("b31becfe-cd73-42dd-98be-171c20f672a7"),
                            CategoryId = new Guid("3c7d953e-61fa-47cb-b263-30c55f364f7d")
                        },
                        new
                        {
                            ProductId = new Guid("378690c5-295d-4955-8860-abbed9c2c9ab"),
                            CategoryId = new Guid("3d87cbf9-e79c-4833-8374-84b0858925c8")
                        },
                        new
                        {
                            ProductId = new Guid("0c02c7af-5bcf-4166-8c9a-974e4e5222ec"),
                            CategoryId = new Guid("7c8006ab-4dbe-40b2-8876-08fa113cf986")
                        },
                        new
                        {
                            ProductId = new Guid("15077ff2-a784-4746-9ba4-5f26cb28bf11"),
                            CategoryId = new Guid("3d87cbf9-e79c-4833-8374-84b0858925c8")
                        },
                        new
                        {
                            ProductId = new Guid("d65d91ae-99e4-48c4-a77a-cd495cb9761f"),
                            CategoryId = new Guid("40d4a750-812b-4364-9027-676bea89216d")
                        });
                });

            modelBuilder.Entity("Catalog.API.Models.ProductCategory", b =>
                {
                    b.HasOne("Catalog.API.Models.Category", "Category")
                        .WithMany("ProductCategories")
                        .HasForeignKey("CategoryId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("Catalog.API.Models.Product", "Product")
                        .WithMany("ProductCategories")
                        .HasForeignKey("ProductId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Category");

                    b.Navigation("Product");
                });

            modelBuilder.Entity("Catalog.API.Models.Category", b =>
                {
                    b.Navigation("ProductCategories");
                });

            modelBuilder.Entity("Catalog.API.Models.Product", b =>
                {
                    b.Navigation("ProductCategories");
                });
#pragma warning restore 612, 618
        }
    }
}
