// <auto-generated />
using System;
using Catalog.API.Data;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;

#nullable disable

namespace Catalog.API.Migrations
{
    [DbContext(typeof(ProductDbContext))]
    [Migration("20260212093328_ProductModelUpdate")]
    partial class ProductModelUpdate
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "8.0.0")
                .HasAnnotation("Relational:MaxIdentifierLength", 63);

            NpgsqlModelBuilderExtensions.UseIdentityByDefaultColumns(modelBuilder);

            modelBuilder.Entity("Catalog.API.Models.Category", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<string>("Description")
                        .IsRequired()
                        .HasMaxLength(1000)
                        .HasColumnType("character varying(1000)");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(300)
                        .HasColumnType("character varying(300)");

                    b.HasKey("Id");

                    b.ToTable("Categories");

                    b.HasData(
                        new
                        {
                            Id = new Guid("e9583ba7-b2a4-41ce-a9a9-215a7ab9b67b"),
                            Description = "Apparel for men",
                            Name = "Men's Clothing"
                        },
                        new
                        {
                            Id = new Guid("19611b52-5995-483b-836c-f18524dd69dc"),
                            Description = "Apparel for women",
                            Name = "Women's Clothing"
                        },
                        new
                        {
                            Id = new Guid("f6345228-d847-4baa-9414-eaad72219af1"),
                            Description = "Apparel for children",
                            Name = "Kids' Clothing"
                        },
                        new
                        {
                            Id = new Guid("a7b37a81-c4c7-416e-abc5-4539b9e3d0fb"),
                            Description = "Shoes, boots, sneakers",
                            Name = "Footwear"
                        },
                        new
                        {
                            Id = new Guid("7bf4843d-4242-4cf7-b8d2-454ad3050dec"),
                            Description = "Belts, hats, scarves, bags",
                            Name = "Accessories"
                        },
                        new
                        {
                            Id = new Guid("f4252c2b-a491-4104-aa76-1412b193811f"),
                            Description = "Activewear, gym clothes",
                            Name = "Sportswear"
                        },
                        new
                        {
                            Id = new Guid("66e3349d-f52a-47d0-a4f3-def5cbc871d6"),
                            Description = "Comfortable home clothing",
                            Name = "Loungewear"
                        },
                        new
                        {
                            Id = new Guid("a3f85702-9ad8-4d83-bdc0-8a4355fa3548"),
                            Description = "Jackets, coats",
                            Name = "Outerwear"
                        },
                        new
                        {
                            Id = new Guid("cc17f01d-4acd-4b2b-8800-3ff8a9a912ce"),
                            Description = "Suits, dresses, gowns",
                            Name = "Formal Wear"
                        },
                        new
                        {
                            Id = new Guid("754a24e0-2591-4910-a181-ce1af6716e77"),
                            Description = "Underwear, pajamas, nightwear",
                            Name = "Underwear & Sleepwear"
                        });
                });

            modelBuilder.Entity("Catalog.API.Models.Product", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("Description")
                        .IsRequired()
                        .HasMaxLength(1000)
                        .HasColumnType("character varying(1000)");

                    b.Property<string>("Image")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<bool>("IsAvailable")
                        .HasColumnType("boolean");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(300)
                        .HasColumnType("character varying(300)");

                    b.Property<decimal>("Price")
                        .HasColumnType("numeric");

                    b.Property<int>("Quantity")
                        .HasColumnType("integer");

                    b.Property<int>("Rating")
                        .HasColumnType("integer");

                    b.Property<string>("Sku")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<DateTime>("UpdatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.HasKey("Id");

                    b.ToTable("Products");

                    b.HasData(
                        new
                        {
                            Id = new Guid("59d041a9-50f4-47d6-b2c4-081f9cf73336"),
                            CreatedAt = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Description = "100% cotton, comfortable fit",
                            Image = "mens-classic-tshirt.jpg",
                            IsAvailable = true,
                            Name = "Men's Classic T-Shirt",
                            Price = 25.99m,
                            Quantity = 0,
                            Rating = 4,
                            Sku = "MEN-TSHIRT-01",
                            UpdatedAt = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified)
                        },
                        new
                        {
                            Id = new Guid("14836d91-3a5b-443a-8c4c-c69ead6bd09e"),
                            CreatedAt = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Description = "Denim, slim fit, dark wash",
                            Image = "mens-slim-jeans.jpg",
                            IsAvailable = true,
                            Name = "Men's Slim Jeans",
                            Price = 49.99m,
                            Quantity = 0,
                            Rating = 5,
                            Sku = "MEN-JEANS-02",
                            UpdatedAt = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified)
                        },
                        new
                        {
                            Id = new Guid("30940b9a-d383-457c-b14c-0d8823cedd36"),
                            CreatedAt = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Description = "Lightweight, floral print",
                            Image = "womens-summer-dress.jpg",
                            IsAvailable = true,
                            Name = "Women's Summer Dress",
                            Price = 39.99m,
                            Quantity = 0,
                            Rating = 5,
                            Sku = "WOM-DRESS-01",
                            UpdatedAt = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified)
                        },
                        new
                        {
                            Id = new Guid("9861557a-7d5b-480b-b0b9-e077c066857b"),
                            CreatedAt = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Description = "Silk blend, long sleeves",
                            Image = "womens-blouse.jpg",
                            IsAvailable = true,
                            Name = "Women's Blouse",
                            Price = 35.50m,
                            Quantity = 0,
                            Rating = 4,
                            Sku = "WOM-BLOUSE-02",
                            UpdatedAt = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified)
                        },
                        new
                        {
                            Id = new Guid("16f91ae1-ad43-4741-bf1a-e75d57418dbd"),
                            CreatedAt = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Description = "Soft cotton, colorful design",
                            Image = "kids-hoodie.jpg",
                            IsAvailable = true,
                            Name = "Kids' Hoodie",
                            Price = 29.99m,
                            Quantity = 0,
                            Rating = 4,
                            Sku = "KID-HOODIE-01",
                            UpdatedAt = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified)
                        },
                        new
                        {
                            Id = new Guid("81868517-1a49-4f41-a296-0f26936b8f7e"),
                            CreatedAt = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Description = "Lightweight and durable",
                            Image = "kids-sneakers.jpg",
                            IsAvailable = true,
                            Name = "Kids' Sneakers",
                            Price = 34.99m,
                            Quantity = 0,
                            Rating = 5,
                            Sku = "KID-SNEAK-01",
                            UpdatedAt = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified)
                        },
                        new
                        {
                            Id = new Guid("f533a0d0-eaeb-48ca-bc30-e348066dc4c3"),
                            CreatedAt = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Description = "Genuine leather, classic buckle",
                            Image = "leather-belt.jpg",
                            IsAvailable = true,
                            Name = "Leather Belt",
                            Price = 19.99m,
                            Quantity = 0,
                            Rating = 4,
                            Sku = "ACC-BELT-01",
                            UpdatedAt = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified)
                        },
                        new
                        {
                            Id = new Guid("692f2039-e00e-4657-94a3-d3db49d93015"),
                            CreatedAt = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Description = "Lightweight with cushioned sole",
                            Image = "mens-running-shoes.jpg",
                            IsAvailable = true,
                            Name = "Men's Running Shoes",
                            Price = 89.99m,
                            Quantity = 0,
                            Rating = 5,
                            Sku = "MEN-RUN-01",
                            UpdatedAt = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified)
                        },
                        new
                        {
                            Id = new Guid("c6f3ab4f-de29-40d7-833f-fbf48e68de09"),
                            CreatedAt = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Description = "Stretchable and comfortable",
                            Image = "womens-yoga-pants.jpg",
                            IsAvailable = true,
                            Name = "Women's Yoga Pants",
                            Price = 45.00m,
                            Quantity = 0,
                            Rating = 4,
                            Sku = "WOM-YOGA-01",
                            UpdatedAt = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified)
                        },
                        new
                        {
                            Id = new Guid("9bf7190d-22c6-4752-a93e-fc6e5bcf183a"),
                            CreatedAt = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Description = "Waterproof and insulated",
                            Image = "winter-jacket.jpg",
                            IsAvailable = true,
                            Name = "Winter Jacket",
                            Price = 129.99m,
                            Quantity = 0,
                            Rating = 5,
                            Sku = "OUT-JACKET-01",
                            UpdatedAt = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified)
                        },
                        new
                        {
                            Id = new Guid("46892596-7481-4727-9741-4ea753f02c80"),
                            CreatedAt = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Description = "Tailored fit, premium fabric",
                            Image = "mens-suit.jpg",
                            IsAvailable = true,
                            Name = "Men's Suit",
                            Price = 249.99m,
                            Quantity = 0,
                            Rating = 5,
                            Sku = "FORM-SUIT-01",
                            UpdatedAt = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified)
                        },
                        new
                        {
                            Id = new Guid("77229aaf-e0b6-40c5-9f3a-166553ca4fdf"),
                            CreatedAt = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Description = "Elegant floor-length gown",
                            Image = "womens-evening-gown.jpg",
                            IsAvailable = true,
                            Name = "Women's Evening Gown",
                            Price = 199.99m,
                            Quantity = 0,
                            Rating = 5,
                            Sku = "FORM-GOWN-01",
                            UpdatedAt = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified)
                        },
                        new
                        {
                            Id = new Guid("226d0753-f1f2-45d1-9da7-2dedfa68c097"),
                            CreatedAt = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Description = "Soft cotton top and pants",
                            Image = "loungewear-set.jpg",
                            IsAvailable = true,
                            Name = "Loungewear Set",
                            Price = 59.99m,
                            Quantity = 0,
                            Rating = 4,
                            Sku = "LOUNGE-SET-01",
                            UpdatedAt = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified)
                        },
                        new
                        {
                            Id = new Guid("b166874f-6799-475a-b322-cd12f226d547"),
                            CreatedAt = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Description = "Comfortable nightwear",
                            Image = "mens-pajama-set.jpg",
                            IsAvailable = true,
                            Name = "Men's Pajama Set",
                            Price = 39.99m,
                            Quantity = 0,
                            Rating = 4,
                            Sku = "UNDER-MEN-01",
                            UpdatedAt = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified)
                        },
                        new
                        {
                            Id = new Guid("7325fc9c-c587-4367-941f-18a12580e3bf"),
                            CreatedAt = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Description = "Soft and cozy sleepwear",
                            Image = "womens-pajama-set.jpg",
                            IsAvailable = true,
                            Name = "Women's Pajama Set",
                            Price = 42.99m,
                            Quantity = 0,
                            Rating = 5,
                            Sku = "UNDER-WOM-01",
                            UpdatedAt = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified)
                        },
                        new
                        {
                            Id = new Guid("586cea93-e806-4660-89da-2ddc892fd208"),
                            CreatedAt = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Description = "Waterproof and insulated",
                            Image = "kids-winter-boots.jpg",
                            IsAvailable = true,
                            Name = "Kids' Winter Boots",
                            Price = 59.99m,
                            Quantity = 0,
                            Rating = 5,
                            Sku = "KID-BOOT-01",
                            UpdatedAt = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified)
                        },
                        new
                        {
                            Id = new Guid("290148e2-985e-4fe1-b59e-9d2e77401cdd"),
                            CreatedAt = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Description = "Breathable material, adjustable",
                            Image = "sports-cap.jpg",
                            IsAvailable = true,
                            Name = "Sports Cap",
                            Price = 14.99m,
                            Quantity = 0,
                            Rating = 4,
                            Sku = "ACC-CAP-01",
                            UpdatedAt = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified)
                        },
                        new
                        {
                            Id = new Guid("55b3439e-7afc-427e-9d7e-b470063d4c04"),
                            CreatedAt = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Description = "Casual and sporty",
                            Image = "womens-sneakers.jpg",
                            IsAvailable = true,
                            Name = "Sneakers for Women",
                            Price = 79.99m,
                            Quantity = 0,
                            Rating = 4,
                            Sku = "WOM-SNEAK-01",
                            UpdatedAt = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified)
                        },
                        new
                        {
                            Id = new Guid("cf6ad59b-f991-4404-a3a3-6fe765b5f570"),
                            CreatedAt = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Description = "Durable and spacious",
                            Image = "backpack.jpg",
                            IsAvailable = true,
                            Name = "Backpack",
                            Price = 49.99m,
                            Quantity = 0,
                            Rating = 4,
                            Sku = "ACC-BAG-01",
                            UpdatedAt = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified)
                        },
                        new
                        {
                            Id = new Guid("53e2055b-3c93-40d9-b1aa-b78105ad9652"),
                            CreatedAt = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Description = "Warm and stylish",
                            Image = "mens-hoodie.jpg",
                            IsAvailable = true,
                            Name = "Men's Hoodie",
                            Price = 59.99m,
                            Quantity = 0,
                            Rating = 4,
                            Sku = "MEN-HOODIE-01",
                            UpdatedAt = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified)
                        });
                });

            modelBuilder.Entity("Catalog.API.Models.ProductCategory", b =>
                {
                    b.Property<Guid>("ProductId")
                        .HasColumnType("uuid");

                    b.Property<Guid>("CategoryId")
                        .HasColumnType("uuid");

                    b.HasKey("ProductId", "CategoryId");

                    b.HasIndex("CategoryId");

                    b.ToTable("ProductCategories");

                    b.HasData(
                        new
                        {
                            ProductId = new Guid("59d041a9-50f4-47d6-b2c4-081f9cf73336"),
                            CategoryId = new Guid("e9583ba7-b2a4-41ce-a9a9-215a7ab9b67b")
                        },
                        new
                        {
                            ProductId = new Guid("14836d91-3a5b-443a-8c4c-c69ead6bd09e"),
                            CategoryId = new Guid("e9583ba7-b2a4-41ce-a9a9-215a7ab9b67b")
                        },
                        new
                        {
                            ProductId = new Guid("30940b9a-d383-457c-b14c-0d8823cedd36"),
                            CategoryId = new Guid("19611b52-5995-483b-836c-f18524dd69dc")
                        },
                        new
                        {
                            ProductId = new Guid("9861557a-7d5b-480b-b0b9-e077c066857b"),
                            CategoryId = new Guid("19611b52-5995-483b-836c-f18524dd69dc")
                        },
                        new
                        {
                            ProductId = new Guid("16f91ae1-ad43-4741-bf1a-e75d57418dbd"),
                            CategoryId = new Guid("f6345228-d847-4baa-9414-eaad72219af1")
                        },
                        new
                        {
                            ProductId = new Guid("81868517-1a49-4f41-a296-0f26936b8f7e"),
                            CategoryId = new Guid("f6345228-d847-4baa-9414-eaad72219af1")
                        },
                        new
                        {
                            ProductId = new Guid("f533a0d0-eaeb-48ca-bc30-e348066dc4c3"),
                            CategoryId = new Guid("7bf4843d-4242-4cf7-b8d2-454ad3050dec")
                        },
                        new
                        {
                            ProductId = new Guid("692f2039-e00e-4657-94a3-d3db49d93015"),
                            CategoryId = new Guid("e9583ba7-b2a4-41ce-a9a9-215a7ab9b67b")
                        },
                        new
                        {
                            ProductId = new Guid("c6f3ab4f-de29-40d7-833f-fbf48e68de09"),
                            CategoryId = new Guid("19611b52-5995-483b-836c-f18524dd69dc")
                        },
                        new
                        {
                            ProductId = new Guid("9bf7190d-22c6-4752-a93e-fc6e5bcf183a"),
                            CategoryId = new Guid("a3f85702-9ad8-4d83-bdc0-8a4355fa3548")
                        },
                        new
                        {
                            ProductId = new Guid("46892596-7481-4727-9741-4ea753f02c80"),
                            CategoryId = new Guid("e9583ba7-b2a4-41ce-a9a9-215a7ab9b67b")
                        },
                        new
                        {
                            ProductId = new Guid("77229aaf-e0b6-40c5-9f3a-166553ca4fdf"),
                            CategoryId = new Guid("19611b52-5995-483b-836c-f18524dd69dc")
                        },
                        new
                        {
                            ProductId = new Guid("226d0753-f1f2-45d1-9da7-2dedfa68c097"),
                            CategoryId = new Guid("66e3349d-f52a-47d0-a4f3-def5cbc871d6")
                        },
                        new
                        {
                            ProductId = new Guid("b166874f-6799-475a-b322-cd12f226d547"),
                            CategoryId = new Guid("754a24e0-2591-4910-a181-ce1af6716e77")
                        },
                        new
                        {
                            ProductId = new Guid("7325fc9c-c587-4367-941f-18a12580e3bf"),
                            CategoryId = new Guid("754a24e0-2591-4910-a181-ce1af6716e77")
                        },
                        new
                        {
                            ProductId = new Guid("586cea93-e806-4660-89da-2ddc892fd208"),
                            CategoryId = new Guid("f6345228-d847-4baa-9414-eaad72219af1")
                        },
                        new
                        {
                            ProductId = new Guid("290148e2-985e-4fe1-b59e-9d2e77401cdd"),
                            CategoryId = new Guid("7bf4843d-4242-4cf7-b8d2-454ad3050dec")
                        },
                        new
                        {
                            ProductId = new Guid("55b3439e-7afc-427e-9d7e-b470063d4c04"),
                            CategoryId = new Guid("a7b37a81-c4c7-416e-abc5-4539b9e3d0fb")
                        },
                        new
                        {
                            ProductId = new Guid("cf6ad59b-f991-4404-a3a3-6fe765b5f570"),
                            CategoryId = new Guid("7bf4843d-4242-4cf7-b8d2-454ad3050dec")
                        },
                        new
                        {
                            ProductId = new Guid("53e2055b-3c93-40d9-b1aa-b78105ad9652"),
                            CategoryId = new Guid("e9583ba7-b2a4-41ce-a9a9-215a7ab9b67b")
                        });
                });

            modelBuilder.Entity("Catalog.API.Models.ProductCategory", b =>
                {
                    b.HasOne("Catalog.API.Models.Category", "Category")
                        .WithMany("ProductCategories")
                        .HasForeignKey("CategoryId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("Catalog.API.Models.Product", "Product")
                        .WithMany("ProductCategories")
                        .HasForeignKey("ProductId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Category");

                    b.Navigation("Product");
                });

            modelBuilder.Entity("Catalog.API.Models.Category", b =>
                {
                    b.Navigation("ProductCategories");
                });

            modelBuilder.Entity("Catalog.API.Models.Product", b =>
                {
                    b.Navigation("ProductCategories");
                });
#pragma warning restore 612, 618
        }
    }
}
