// <auto-generated />
using System;
using Catalog.API.Data;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;

#nullable disable

namespace Catalog.API.Migrations
{
    [DbContext(typeof(ProductDbContext))]
    partial class ProductDbContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "8.0.0")
                .HasAnnotation("Relational:MaxIdentifierLength", 63);

            NpgsqlModelBuilderExtensions.UseIdentityByDefaultColumns(modelBuilder);

            modelBuilder.Entity("Catalog.API.Models.Category", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<string>("Description")
                        .IsRequired()
                        .HasMaxLength(1000)
                        .HasColumnType("character varying(1000)");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(300)
                        .HasColumnType("character varying(300)");

                    b.HasKey("Id");

                    b.ToTable("Categories");

                    b.HasData(
                        new
                        {
                            Id = new Guid("00000000-0000-0000-0000-000000000001"),
                            Description = "Apparel and accessories for men",
                            Name = "Men"
                        },
                        new
                        {
                            Id = new Guid("00000000-0000-0000-0000-000000000002"),
                            Description = "Apparel and accessories for women",
                            Name = "Women"
                        },
                        new
                        {
                            Id = new Guid("00000000-0000-0000-0000-000000000003"),
                            Description = "Clothing, shoes, and accessories for children",
                            Name = "Kids"
                        },
                        new
                        {
                            Id = new Guid("00000000-0000-0000-0000-000000000004"),
                            Description = "Shoes, boots, sneakers, and sandals",
                            Name = "Footwear"
                        },
                        new
                        {
                            Id = new Guid("00000000-0000-0000-0000-000000000005"),
                            Description = "Bags, belts, hats, jewelry, and more",
                            Name = "Accessories"
                        },
                        new
                        {
                            Id = new Guid("00000000-0000-0000-0000-000000000006"),
                            Description = "Athletic wear, gym apparel, and sports accessories",
                            Name = "Sportswear"
                        },
                        new
                        {
                            Id = new Guid("00000000-0000-0000-0000-000000000007"),
                            Description = "Jackets, coats, and seasonal outerwear",
                            Name = "Outerwear"
                        },
                        new
                        {
                            Id = new Guid("00000000-0000-0000-0000-000000000008"),
                            Description = "Suits, dresses, and other formal clothing",
                            Name = "Formal Wear"
                        },
                        new
                        {
                            Id = new Guid("00000000-0000-0000-0000-000000000009"),
                            Description = "Casual and comfortable clothing for home",
                            Name = "Loungewear"
                        },
                        new
                        {
                            Id = new Guid("00000000-0000-0000-0000-000000000010"),
                            Description = "Undergarments, pajamas, and nightwear",
                            Name = "Underwear & Sleepwear"
                        });
                });

            modelBuilder.Entity("Catalog.API.Models.Product", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("Description")
                        .IsRequired()
                        .HasMaxLength(1000)
                        .HasColumnType("character varying(1000)");

                    b.Property<string>("ImageFile")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<bool>("IsAvailable")
                        .HasColumnType("boolean");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(300)
                        .HasColumnType("character varying(300)");

                    b.Property<decimal>("Price")
                        .HasColumnType("numeric");

                    b.Property<int>("Rating")
                        .HasColumnType("integer");

                    b.Property<string>("Sku")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<DateTime>("UpdatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.HasKey("Id");

                    b.ToTable("Products");

                    b.HasData(
                        new
                        {
                            Id = new Guid("8b159607-19dd-4668-8e60-5c0dae465ef9"),
                            CreatedAt = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Description = "100% cotton, comfortable fit",
                            ImageFile = "images/products/mens-classic-tshirt.jpg",
                            IsAvailable = true,
                            Name = "Men's Classic T-Shirt",
                            Price = 25.99m,
                            Rating = 4,
                            Sku = "MEN-TSHIRT-01",
                            UpdatedAt = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified)
                        },
                        new
                        {
                            Id = new Guid("f15ea535-5296-44e0-9bc4-657d9309d860"),
                            CreatedAt = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Description = "Denim, slim fit, dark wash",
                            ImageFile = "images/products/mens-slim-jeans.jpg",
                            IsAvailable = true,
                            Name = "Men's Slim Jeans",
                            Price = 49.99m,
                            Rating = 5,
                            Sku = "MEN-JEANS-02",
                            UpdatedAt = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified)
                        },
                        new
                        {
                            Id = new Guid("676794d3-a51e-40ef-a8d7-a51f59cac341"),
                            CreatedAt = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Description = "Lightweight, floral print",
                            ImageFile = "images/products/womens-summer-dress.jpg",
                            IsAvailable = true,
                            Name = "Women's Summer Dress",
                            Price = 39.99m,
                            Rating = 5,
                            Sku = "WOM-DRESS-01",
                            UpdatedAt = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified)
                        },
                        new
                        {
                            Id = new Guid("f9602190-2b29-48da-8c1b-0ca40595104d"),
                            CreatedAt = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Description = "Silk blend, long sleeves",
                            ImageFile = "images/products/womens-blouse.jpg",
                            IsAvailable = true,
                            Name = "Women's Blouse",
                            Price = 35.50m,
                            Rating = 4,
                            Sku = "WOM-BLOUSE-02",
                            UpdatedAt = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified)
                        },
                        new
                        {
                            Id = new Guid("1542099c-01fc-4cc5-9353-7a337b5dde2b"),
                            CreatedAt = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Description = "Soft cotton, colorful design",
                            ImageFile = "images/products/kids-hoodie.jpg",
                            IsAvailable = true,
                            Name = "Kids' Hoodie",
                            Price = 29.99m,
                            Rating = 4,
                            Sku = "KID-HOODIE-01",
                            UpdatedAt = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified)
                        },
                        new
                        {
                            Id = new Guid("7838671a-7933-4074-a72e-d3e22720b940"),
                            CreatedAt = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Description = "Lightweight and durable",
                            ImageFile = "images/products/kids-sneakers.jpg",
                            IsAvailable = true,
                            Name = "Kids' Sneakers",
                            Price = 34.99m,
                            Rating = 5,
                            Sku = "KID-SNEAK-01",
                            UpdatedAt = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified)
                        },
                        new
                        {
                            Id = new Guid("53e3c819-3e9b-4a69-856c-e8e67f61b90e"),
                            CreatedAt = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Description = "Genuine leather, classic buckle",
                            ImageFile = "images/products/leather-belt.jpg",
                            IsAvailable = true,
                            Name = "Leather Belt",
                            Price = 19.99m,
                            Rating = 4,
                            Sku = "ACC-BELT-01",
                            UpdatedAt = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified)
                        },
                        new
                        {
                            Id = new Guid("c77705e7-4b21-4944-86d2-9ae861d35637"),
                            CreatedAt = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Description = "Lightweight with cushioned sole",
                            ImageFile = "images/products/mens-running-shoes.jpg",
                            IsAvailable = true,
                            Name = "Men's Running Shoes",
                            Price = 89.99m,
                            Rating = 5,
                            Sku = "MEN-RUN-01",
                            UpdatedAt = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified)
                        },
                        new
                        {
                            Id = new Guid("30b9e589-2f04-438e-bed8-890bea98da11"),
                            CreatedAt = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Description = "Stretchable and comfortable",
                            ImageFile = "images/products/womens-yoga-pants.jpg",
                            IsAvailable = true,
                            Name = "Women's Yoga Pants",
                            Price = 45.00m,
                            Rating = 4,
                            Sku = "WOM-YOGA-01",
                            UpdatedAt = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified)
                        },
                        new
                        {
                            Id = new Guid("7d6c56b3-0d4a-47b6-b278-91364e267ad5"),
                            CreatedAt = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Description = "Waterproof and insulated",
                            ImageFile = "images/products/winter-jacket.jpg",
                            IsAvailable = true,
                            Name = "Winter Jacket",
                            Price = 129.99m,
                            Rating = 5,
                            Sku = "OUT-JACKET-01",
                            UpdatedAt = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified)
                        },
                        new
                        {
                            Id = new Guid("bab7ec60-1090-492b-aaa8-e0a68a4b0d9a"),
                            CreatedAt = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Description = "Tailored fit, premium fabric",
                            ImageFile = "images/products/mens-suit.jpg",
                            IsAvailable = true,
                            Name = "Men's Suit",
                            Price = 249.99m,
                            Rating = 5,
                            Sku = "FORM-SUIT-01",
                            UpdatedAt = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified)
                        },
                        new
                        {
                            Id = new Guid("e87c0474-3f3e-4ae9-9ffe-ecf209659724"),
                            CreatedAt = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Description = "Elegant floor-length gown",
                            ImageFile = "images/products/womens-evening-gown.jpg",
                            IsAvailable = true,
                            Name = "Women's Evening Gown",
                            Price = 199.99m,
                            Rating = 5,
                            Sku = "FORM-GOWN-01",
                            UpdatedAt = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified)
                        },
                        new
                        {
                            Id = new Guid("d5375352-fabb-4a8a-b341-76b4de6d3a46"),
                            CreatedAt = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Description = "Soft cotton top and pants",
                            ImageFile = "images/products/loungewear-set.jpg",
                            IsAvailable = true,
                            Name = "Loungewear Set",
                            Price = 59.99m,
                            Rating = 4,
                            Sku = "LOUNGE-SET-01",
                            UpdatedAt = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified)
                        },
                        new
                        {
                            Id = new Guid("1d7e3d34-d0a7-406a-b0e1-5957294951a7"),
                            CreatedAt = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Description = "Comfortable nightwear",
                            ImageFile = "images/products/mens-pajama-set.jpg",
                            IsAvailable = true,
                            Name = "Men's Pajama Set",
                            Price = 39.99m,
                            Rating = 4,
                            Sku = "UNDER-MEN-01",
                            UpdatedAt = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified)
                        },
                        new
                        {
                            Id = new Guid("fee83c9a-bca2-4523-9596-6e652c49e387"),
                            CreatedAt = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Description = "Soft and cozy sleepwear",
                            ImageFile = "images/products/womens-pajama-set.jpg",
                            IsAvailable = true,
                            Name = "Women's Pajama Set",
                            Price = 42.99m,
                            Rating = 5,
                            Sku = "UNDER-WOM-01",
                            UpdatedAt = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified)
                        },
                        new
                        {
                            Id = new Guid("ded587bf-ffd7-4b26-8548-fea3a8bd931b"),
                            CreatedAt = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Description = "Waterproof and insulated",
                            ImageFile = "images/products/kids-winter-boots.jpg",
                            IsAvailable = true,
                            Name = "Kids' Winter Boots",
                            Price = 59.99m,
                            Rating = 5,
                            Sku = "KID-BOOT-01",
                            UpdatedAt = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified)
                        },
                        new
                        {
                            Id = new Guid("87ac07a4-ab43-4375-888b-4c5016e44c3b"),
                            CreatedAt = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Description = "Breathable material, adjustable",
                            ImageFile = "images/products/sports-cap.jpg",
                            IsAvailable = true,
                            Name = "Sports Cap",
                            Price = 14.99m,
                            Rating = 4,
                            Sku = "ACC-CAP-01",
                            UpdatedAt = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified)
                        },
                        new
                        {
                            Id = new Guid("013739f0-327d-4a1d-b044-b2e3c9ffbe52"),
                            CreatedAt = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Description = "Casual and sporty",
                            ImageFile = "images/products/womens-sneakers.jpg",
                            IsAvailable = true,
                            Name = "Sneakers for Women",
                            Price = 79.99m,
                            Rating = 4,
                            Sku = "WOM-SNEAK-01",
                            UpdatedAt = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified)
                        },
                        new
                        {
                            Id = new Guid("43b45b3c-11e3-480c-978c-566f3d13f190"),
                            CreatedAt = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Description = "Durable and spacious",
                            ImageFile = "images/products/backpack.jpg",
                            IsAvailable = true,
                            Name = "Backpack",
                            Price = 49.99m,
                            Rating = 4,
                            Sku = "ACC-BAG-01",
                            UpdatedAt = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified)
                        },
                        new
                        {
                            Id = new Guid("24dd06cd-d25d-4fb7-81de-bbcfcd71796e"),
                            CreatedAt = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Description = "Warm and stylish",
                            ImageFile = "images/products/mens-hoodie.jpg",
                            IsAvailable = true,
                            Name = "Men's Hoodie",
                            Price = 59.99m,
                            Rating = 4,
                            Sku = "MEN-HOODIE-01",
                            UpdatedAt = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified)
                        });
                });

            modelBuilder.Entity("Catalog.API.Models.ProductCategory", b =>
                {
                    b.Property<Guid>("ProductId")
                        .HasColumnType("uuid");

                    b.Property<Guid>("CategoryId")
                        .HasColumnType("uuid");

                    b.HasKey("ProductId", "CategoryId");

                    b.HasIndex("CategoryId");

                    b.ToTable("ProductCategory");
                });

            modelBuilder.Entity("Catalog.API.Models.ProductCategory", b =>
                {
                    b.HasOne("Catalog.API.Models.Category", "Category")
                        .WithMany("ProductCategories")
                        .HasForeignKey("CategoryId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("Catalog.API.Models.Product", "Product")
                        .WithMany("ProductCategories")
                        .HasForeignKey("ProductId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Category");

                    b.Navigation("Product");
                });

            modelBuilder.Entity("Catalog.API.Models.Category", b =>
                {
                    b.Navigation("ProductCategories");
                });

            modelBuilder.Entity("Catalog.API.Models.Product", b =>
                {
                    b.Navigation("ProductCategories");
                });
#pragma warning restore 612, 618
        }
    }
}
